# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "antoszyk-demo/app"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "antoszykdemo/app"
    working_directory: "${{clone}}"
    tags: 
      - "${{CF_BRANCH_TAG_NORMALIZED}}"
      - latest
      - "${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"
  
  tests:
    stage: "test"
    type: parallel
    steps:
      poetry-test:
        title: "poetry test"
        type: "freestyle" # Run any command
        image: "python:3.7"
        working_directory: "${{clone}}" # Running command where code cloned
        commands:
          - "pip install poetry"
          - "poetry config virtualenvs.create false"
          - "poetry install --no-root"
          - "poetry run pytest --junitxml=report.xml tests/"
      test:
        title: "Running test"
        type: "freestyle" # Run any command
        image: "ubuntu:latest" # The image in which command will be executed
        working_directory: "${{clone}}" # Running command where code cloned
        commands:
          - "ls"
      scan:
        title: Scan images
        type: freestyle
        image: "aquasec/trivy" # The image in which command will be executed
        commands:
          - "trivy antoszykdemo/app"
