# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "antoszyk-demo/app"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "antoszykdemo/app"
    working_directory: "${{clone}}"
    tags: 
      - "${{CF_BRANCH_TAG_NORMALIZED}}"
      - latest
      - "${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"
  
  tests:
    stage: "test"
    type: parallel
    steps:
      poetry-test:
        title: "poetry test"
        type: "freestyle" # Run any command
        image: "antoszykdemo/app:master"
        working_directory: "${{clone}}" # Running command where code cloned
        commands:
          - "poetry run pytest --junitxml=report.xml tests/"
      test:
        title: "Running test"
        type: "freestyle" # Run any command
        image: "ubuntu:latest" # The image in which command will be executed
        working_directory: "${{clone}}" # Running command where code cloned
        commands:
          - "ls"
      scan:
        title: Scan images
        type: freestyle
        image: "aquasec/trivy" # The image in which command will be executed
        commands:
          - "trivy antoszykdemo/app"

  deploy:
    type: helm
    stage: "deploy"
    arguments:
      action: install
      chart_name: "${{clone}}/chart"
      release_name: cf-app
      helm_version: 3.0.1
      kube_context: staging
      namespace: demo
      skip_cf_stable_helm_repo: true
      credentials_in_arguments: true
      custom_values:
        - 'ingress.enabled=true'
        - 'ingress.hosts[0].host=demo.app-demo.cf'
        - "image.tag=${{CF_SHORT_REVISION}}"
